language: go

go:
  - stable
env:
  global:
    secure: ImmVcbZ1SRfEVYGvmZhUPWvi0sWh5joE1OcKt7XH/qDjeeWd1bovBqigYdV3x2Nt5sAc1v8Qqfk1io11o+UVMuNcCn9eU+XEVoKJNc0FatGGsGM18t8iwxSvZ/6L29FOwLNOWlug/oVX/6wWgFt+4+p5Ld5+9Rv0rhsImDPnEmZUwJp8TvwUwrC02uWASegZIaa+KSx4fegJjScxvoL+Q6ymAmPDVS3vq84bW+UmOputTYAvyeDElp32K//C+AFzpcz/4u8E9SbeVGc3ZSCvQfZ2VgxOjQMMB1E104fjE8oBxH8XZ6Ei7S9in0i7YUkcHsF0cSWBxJ3/PCWyvFl+dlU1qzSMbIu3d3o94xJrRq+bX/GDtFa5F65wFH+XznkVLD6zSwMDExLNr4KPmf1Wqk0KucOQqG2Voux9C3PorC8gRJuKrWLBrpKk2RVXWuAEe8in99CBzyGbKD2q3TWW3syMgVgScx6Fp3rAQPm+62qNOvLcvguGLl0ltNdNMtqZVjcbvxK2SHxr+GGmXB5rgl8Tk20GUT/BjKZNx7PvJBqV6EN1coGHDqAtMvzOcdPJ0mmP6657O2pgZ4f6SF0XCK6OvPR9bVwOpQoJUfX+zkeejkbt5aREgf19b2ii365eBj6zQyTF5dX8hx3F7OaRi5L5Wp5idPaI6xMI5jEu02I=

after_success:
  - bash update_documentation.sh
